# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 98
indent-width = 4


[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"


[lint]

# https://docs.astral.sh/ruff/rules/
# General
select = [
  "E",     # pycodestyle
  "W",     # pycodestyle
  "D",     # pydocstyle
  "PL",    # pylint
  "F",
  "I",
  "C4",
  "C",
  "SIM",
  "B",
  "A",
  "ASYNC",
  "PERF",
  "RUF",
]

# Extra long
# select = ["ASYNC", "B", "A", "C4", "Q", "RET", "SIM", "SLOT", "TD", "TC",
# "PERF", "I", "D", "DOC", "F", "PL", "UP", "FURB", "RUF", "TRY"]
ignore = [
  "C901", # McCabe complexity warning
  "E501", # Line too long
  "E722", # Do not use bare `except`
  "PLC0415" # Import statement should be at top of file
]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"


[lint.pydocstyle]
convention = "google"
