[project]
name = "megatui"
version = "0.0.1"
description = "Terminal user interface for MEGA"
requires-python = ">=3.13"
readme="README.md"
dependencies = [
    "textual-dev>=1.7.0",
    "textual[dev]>=3.1.0",
]


[tool.pyright]
exclude = ["**/node_modules",
    "**/__pycache__",
    "src/experimental",
    "src/typestubs"
]
# ignore = ["src/oldstuff"]
defineConstant = { DEBUG = true }
# stubPath = "src/stubs"

reportMissingImports = "error"
reportMissingTypeStubs = false
reportUnusedCallResult = false
reportUnannotatedClassAttribute = false

pythonVersion = "3.13"
pythonPlatform = "Linux"

# executionEnvironments = [
  # { root = "src/web", pythonVersion = "3.5", pythonPlatform = "Windows", extraPaths = [ "src/service_libs" ], reportMissingImports = "warning" },
  # { root = "src/sdk", pythonVersion = "3.0", extraPaths = [ "src/backend" ] },
  # { root = "src/tests", extraPaths = ["src/tests/e2e", "src/sdk" ]},
  # { root = "src" }
# ]
